### ISSUE TITLE
Los errores se muestran "en la línea siguiente"

### ISSUE THREAD

**Issue by faloi** [gobstones/gs-weblang-core#13]
No me animo a decir que basta con restarle 1...

**Comment by fidel-ml** [comment]
Para mí que es un tema de tokens... Te avisa el error en el token en el que
lo detecta, que es necesariamente el de la línea siguiente.
Definitivamente no es restarle uno a la línea, sino al token (o
construcción que el token involucra...)
FF

2016-08-16 8:28 GMT-03:00 Federico Aloi notifications@github.com:
