### ISSUE TITLE
Vista de Tablero inicial y Resultados exactamente iguales

### ISSUE THREAD

**Issue by faloi** [gobstones/gs-weblang-core#32]
* Agregar el selector de vestimentas a Tablero inicial. Si la vestimenta está prendida no se tiene que poder editar el tablero en absoluto.
* Agregar el editor de tamaño a Resultados (que aparezca deshabilitado).

**Comment by fidel-ml** [comment]
También botón de vaciar tablero.


2016-11-30 12:33 GMT-03:00 Federico Aloi <notifications@github.com>:
