### ISSUE TITLE
Mejorar mensaje foreach_expects_an_identifier 

### ISSUE THREAD

**Issue by faloi** [gobstones/gs-weblang-core#45]
En este ejemplo, debería arrojar: `5 no es un nombre válido para un índice`. 

```
foreach 5 in [1,3,4] {
     repeat(i) {Poner(Verde)}
     Mover(Este)
}
```

Ver #44, se podría reutilizar ese mensaje parametrizando el `para <%= tipo_de_nombre %>`, pudiendo ser `una variable`, `un índice`, `un parámetro`.
(Variable en una asignación `5 := 3`,
índice en un foreach `foreach 5 in`,
parámetro en una definción de procedimiento o función `procedure P(5) {`)

**Comment by afska** [comment]
No sé si me copa unificarlos. Es incómodo para testear y desde el código tendría que traducir el "tipo de nombre" al tirar el error. Ej:
```js
throw new ParserError(token, { code: 'invalid_name', detail: { value: token.value, nameType: locales.get('index') } })
```

**Comment by faloi** [comment]
No unifique pues, usted es el programador. :stuck_out_tongue:

**Comment by afska** [comment]
Encontré una forma piola de hacerlo, así que al final sí (?).

Ahora hago un PR...
