### ISSUE TITLE
'Something has gone very wrong' cuando se intenta ejecutar un programa vacío

### ISSUE THREAD

**Issue by flbulgarelli** [gobstones/gs-weblang-core#57]
Cuando envío un programa vacío, `weblang-core` responde lo siguiente: 

```json
{"status":"all_is_broken_error","message":"Something has gone very wrong","detail":{},"moreDetail":"Cannot read property 'range' of null"}
```

Esto lo estoy pudiendo reproducir desde mumuki, así que también podría ser un bug del runner, pero sospecho que el problema viene de más adentro.

**Comment by fidel-ml** [comment]
Un programa vacío debería tener como efecto no hacer nada...
FF

2017-05-24 11:10 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by faloi** [comment]
Ojo, que @fidel-ml debe estar pensando en

```
program {}
```

pero @flbulgarelli debe estar hablando de 

```
```

**Comment by fidel-ml** [comment]
No. Para mí ambos deberían ser equivalentes. Aunque ahora que l pienso,
podríamos discutir si el string vacío debería o no ser un error. En caso de
que sea un error, debería ser el mismo que si hubiese procedimientos pero
no program (y de hecho, no entiendo por qué sería diferente... Si lo
implementás como corresponde, debería ser así...)
FF

**Comment by faloi** [comment]
Hoy en día, PyGobstones tiene dos mensajes distintos:

* Ante string vacío, arroja `No se puede ejecutar un programa vacío.`
* Ante programa sin bloque `program`, arroja `El programa debería tener un punto de entrada (procedimiento Main o bloque program).`.

Más allá de eso, coincido con vos; en ambos casos debería decir algo como `El programa debe definir un punto de entrada.`; aunque no sé si "punto de entrada" es la expresión que más feliz me hace...

**Comment by fidel-ml** [comment]
Yo diría que en ambos casos diga "Falta la definición del programa".
FF
